// ISO 3166-1 alpha-3 country code to flag emoji mapping.
const STOREFRONT_FLAGS: Record<string, string> = {
  USA: "🇺🇸",
  CHN: "🇨🇳",
  GBR: "🇬🇧",
  JPN: "🇯🇵",
  KOR: "🇰🇷",
  DEU: "🇩🇪",
  FRA: "🇫🇷",
  ITA: "🇮🇹",
  ESP: "🇪🇸",
  CAN: "🇨🇦",
  AUS: "🇦🇺",
  IND: "🇮🇳",
  BRA: "🇧🇷",
  MEX: "🇲🇽",
  RUS: "🇷🇺",
  TWN: "🇹🇼",
  HKG: "🇭🇰",
  SRB: "🇷🇸",
  NLD: "🇳🇱",
  SWE: "🇸🇪",
  NOR: "🇳🇴",
  DNK: "🇩🇰",
  FIN: "🇫🇮",
  POL: "🇵🇱",
  TUR: "🇹🇷",
  IDN: "🇮🇩",
  THA: "🇹🇭",
  VNM: "🇻🇳",
  MYS: "🇲🇾",
  PHL: "🇵🇭",
  ARE: "🇦🇪",
  SAU: "🇸🇦",
  ISR: "🇮🇱",
  EGY: "🇪🇬",
  ZAF: "🇿🇦",
  NGA: "🇳🇬",
  KEN: "🇰🇪",
  ARG: "🇦🇷",
  CHL: "🇨🇱",
  COL: "🇨🇴",
  PER: "🇵🇪",
  UKR: "🇺🇦",
  ROU: "🇷🇴",
  CHE: "🇨🇭",
  AUT: "🇦🇹",
  BEL: "🇧🇪",
  PRT: "🇵🇹",
  GRC: "🇬🇷",
  CZE: "🇨🇿",
  HUN: "🇭🇺",
  NZL: "🇳🇿",
  SGP: "🇸🇬",
};

export function getStorefrontFlag(storefront: string): string {
  return STOREFRONT_FLAGS[storefront.toUpperCase()] ?? "";
}
